spring:
  datasource:
    url: jdbc:mysql://192.168.0.214:3307/ocat?serverTimezone=GMT%2B8
    username: root
    password: root
code-generator:
  author: stone-98
  includeTable:
    - application
  projectPath: E:\IdeaWorkSpace\am
  parentPackage: com.ocat.am

